# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimize_layout_exact_cpp <- function(initial_positions, dissimilarity_matrix, threshold_matrix, degrees, edge_i, edge_j, edge_dist, edge_thresh, n_iter, k0, cooling_rate, c_repulsion, relative_epsilon, convergence_window, convergence_check_freq, verbose) {
    .Call(`_topolow_optimize_layout_exact_cpp`, initial_positions, dissimilarity_matrix, threshold_matrix, degrees, edge_i, edge_j, edge_dist, edge_thresh, n_iter, k0, cooling_rate, c_repulsion, relative_epsilon, convergence_window, convergence_check_freq, verbose)
}

